from __future__ import annotations

LITERATURE_ROWS = [
    {
        "family": "Momentum / SGD",
        "representative_method": "SGD with momentum",
        "source_title": "On the importance of initialization and momentum in deep learning",
        "source_url": "https://proceedings.mlr.press/v28/sutskever13.html",
        "what_it_does": "Accumulates a velocity vector and follows a smoothed gradient direction.",
        "direction_or_transform": "Transforms gradient into velocity; does not choose among multiple candidate directions.",
        "scope": "Global / per-parameter",
        "already_covers": "Low-state directional persistence and strong practical baselines.",
        "difference_from_bcdo_reference": "BCDO explicitly selects blockwise directions from a candidate pool instead of using one momentum recursion.",
        "required_baseline": "sgd_momentum",
    },
    {
        "family": "RMSProp",
        "representative_method": "RMSProp",
        "source_title": "Neural Networks for Machine Learning, Lecture 6e",
        "source_url": "https://www.cs.toronto.edu/~hinton/coursera/lecture6/lec6.pdf",
        "what_it_does": "Normalizes updates by an EMA of squared gradients.",
        "direction_or_transform": "Per-parameter scaling of the gradient; no candidate selection.",
        "scope": "Per-parameter",
        "already_covers": "Cheap adaptivity and strong small/noisy benchmark performance.",
        "difference_from_bcdo_reference": "BCDO keeps step magnitude separate and focuses on blockwise direction trust rather than coordinate-wise variance scaling.",
        "required_baseline": "rmsprop",
    },
    {
        "family": "Adam / AdamW",
        "representative_method": "AdamW",
        "source_title": "Decoupled Weight Decay Regularization",
        "source_url": "https://arxiv.org/abs/1711.05101",
        "what_it_does": "Uses first and second moments with decoupled weight decay.",
        "direction_or_transform": "Transforms the gradient through EMA momentum and variance normalization.",
        "scope": "Per-parameter",
        "already_covers": "The standard strong adaptive baseline.",
        "difference_from_bcdo_reference": "BCDO is not an Adam-family moment method; it stores block trust and direction memories instead of Adam moments.",
        "required_baseline": "adamw",
    },
    {
        "family": "Lion",
        "representative_method": "Lion",
        "source_title": "Symbolic Discovery of Optimization Algorithms",
        "source_url": "https://arxiv.org/abs/2302.06675",
        "what_it_does": "Uses sign momentum updates with low state overhead.",
        "direction_or_transform": "Transforms the gradient into a signed momentum direction.",
        "scope": "Per-parameter",
        "already_covers": "Low-memory momentum-like direction control.",
        "difference_from_bcdo_reference": "BCDO chooses blockwise directions from several structured candidates instead of committing to a single signed-momentum rule.",
        "required_baseline": "lion",
    },
    {
        "family": "Muon / matrix orthogonalization",
        "representative_method": "Muon",
        "source_title": "Muon is Scalable for LLM Training",
        "source_url": "https://arxiv.org/abs/2502.16982",
        "what_it_does": "Orthogonalizes matrix updates, typically via Newton-Schulz or related matrix steps.",
        "direction_or_transform": "Transforms matrix gradients into orthogonalized matrix directions.",
        "scope": "Matrix-wise / blockwise",
        "already_covers": "Matrix geometry and orthogonalized updates.",
        "difference_from_bcdo_reference": "BCDO may include a Muon-like candidate, but only as one option inside a broader blockwise trust-and-selection rule.",
        "required_baseline": "muon_hybrid",
    },
    {
        "family": "Shampoo",
        "representative_method": "Shampoo",
        "source_title": "Shampoo: Preconditioned Stochastic Tensor Optimization",
        "source_url": "https://arxiv.org/abs/1802.09568",
        "what_it_does": "Uses tensor-mode preconditioners for structured second-order scaling.",
        "direction_or_transform": "Transforms gradients with block/tensor preconditioners.",
        "scope": "Tensor / block-wise",
        "already_covers": "Structured preconditioning with heavy compute/state cost.",
        "difference_from_bcdo_reference": "BCDO is not a tensor preconditioner; it is a candidate-direction selector with lightweight block memory.",
        "required_baseline": "muon_hybrid",
    },
    {
        "family": "K-FAC / natural gradient",
        "representative_method": "K-FAC",
        "source_title": "Optimizing Neural Networks with Kronecker-factored Approximate Curvature",
        "source_url": "https://arxiv.org/abs/1503.05671",
        "what_it_does": "Approximates natural-gradient curvature with Kronecker factors.",
        "direction_or_transform": "Transforms gradients with an approximate inverse curvature matrix.",
        "scope": "Layer / block-wise",
        "already_covers": "Curvature-aware structured updates.",
        "difference_from_bcdo_reference": "BCDO does not estimate curvature; it evaluates candidate directions by trust signals such as coherence and recoverability.",
        "required_baseline": "adamw",
    },
    {
        "family": "SAM / ASAM",
        "representative_method": "SAM",
        "source_title": "Sharpness-Aware Minimization for Efficiently Improving Generalization",
        "source_url": "https://arxiv.org/abs/2010.01412",
        "what_it_does": "Optimizes for flat neighborhoods by solving a local min-max problem.",
        "direction_or_transform": "Transforms the objective / gradient using a perturb-and-recompute step.",
        "scope": "Global / layer-wise perturbation",
        "already_covers": "Neighborhood robustness and flatness-aware updates.",
        "difference_from_bcdo_reference": "BCDO uses cheap blockwise perturbation only to gate candidate trust, not to redefine the full objective.",
        "required_baseline": "adamw",
    },
    {
        "family": "Gradient surgery",
        "representative_method": "PCGrad",
        "source_title": "Gradient Surgery for Multi-Task Learning",
        "source_url": "https://arxiv.org/abs/2001.06782",
        "what_it_does": "Projects conflicting task gradients away from one another.",
        "direction_or_transform": "Selects/projectively edits a gradient combination across task losses.",
        "scope": "Task-global / shared-parameter",
        "already_covers": "Explicit conflict projection when multiple loss gradients are available.",
        "difference_from_bcdo_reference": "BCDO works with single-task blocks too and compares a richer candidate pool than pairwise task projections.",
        "required_baseline": "magneto_hamiltonian_adam",
    },
    {
        "family": "Conflict-aware MTL",
        "representative_method": "CAGrad",
        "source_title": "Conflict-Averse Gradient Descent for Multi-task learning",
        "source_url": "https://openreview.net/forum?id=_61Qh8tULj_",
        "what_it_does": "Balances average descent with worst-task local improvement.",
        "direction_or_transform": "Chooses a joint gradient direction under conflict constraints.",
        "scope": "Task-global",
        "already_covers": "Conflict-aware direction selection for multi-loss settings.",
        "difference_from_bcdo_reference": "BCDO operates blockwise and does not require multiple explicit task gradients to define its trust rule.",
        "required_baseline": "magneto_hamiltonian_adam",
    },
    {
        "family": "Lookahead",
        "representative_method": "Lookahead",
        "source_title": "Lookahead Optimizer: k steps forward, 1 step back",
        "source_url": "https://papers.nips.cc/paper_files/paper/2019/file/90fd4f88f588ae64038134f1eeaa023f-Paper.pdf",
        "what_it_does": "Averages fast inner optimizer trajectories with slower outer steps.",
        "direction_or_transform": "Wraps another optimizer rather than defining a new local direction rule.",
        "scope": "Global",
        "already_covers": "Trajectory smoothing and schedule robustness.",
        "difference_from_bcdo_reference": "BCDO makes block-local direction choices directly; it is not a two-timescale wrapper.",
        "required_baseline": "adamw",
    },
    {
        "family": "Learned optimizers",
        "representative_method": "VeLO",
        "source_title": "VeLO: Training Versatile Learned Optimizers by Scaling Up",
        "source_url": "https://arxiv.org/abs/2211.09760",
        "what_it_does": "Meta-learns an optimizer across many tasks.",
        "direction_or_transform": "Learns update transformations from data instead of hand-specifying the rule.",
        "scope": "Global / meta-learned",
        "already_covers": "Large-scale learned optimization policies.",
        "difference_from_bcdo_reference": "BCDO is hand-specified and interpretable, with explicit block trust components instead of a learned policy.",
        "required_baseline": "adamw",
    },
    {
        "family": "Block coordinate / direction methods",
        "representative_method": "Block coordinate descent",
        "source_title": "Efficiency of Coordinate Descent Methods on Huge-Scale Optimization Problems",
        "source_url": "https://link.springer.com/article/10.1007/s10107-012-0597-5",
        "what_it_does": "Optimizes by choosing coordinates or blocks to update.",
        "direction_or_transform": "Selects coordinates/blocks, often with simple local descent rules.",
        "scope": "Coordinate / block-wise",
        "already_covers": "Explicit block structure and block scheduling.",
        "difference_from_bcdo_reference": "BCDO updates all blocks but selects different candidate directions inside each block based on trust.",
        "required_baseline": "sgd_momentum",
    },
    {
        "family": "Trust-region methods",
        "representative_method": "Trust-region gradient methods",
        "source_title": "Trust Region Methods",
        "source_url": "https://epubs.siam.org/doi/book/10.1137/1.9780898719857",
        "what_it_does": "Limits step size according to a local trust model.",
        "direction_or_transform": "Uses trust to scale or reject steps.",
        "scope": "Global / block-wise depending on method",
        "already_covers": "Classical step acceptance and step scaling.",
        "difference_from_bcdo_reference": "BCDO uses trust to rank discrete candidate directions inside each block, not just to scale one search direction.",
        "required_baseline": "adamw",
    },
    {
        "family": "Evolutionary / black-box search",
        "representative_method": "CMA-ES",
        "source_title": "Completely Derandomized Self-Adaptation in Evolution Strategies",
        "source_url": "https://docslib.org/doc/156104/completely-derandomized-self-adaptation-in-evolution-strategies",
        "what_it_does": "Samples directions from a search distribution rather than following backpropagation gradients directly.",
        "direction_or_transform": "Samples candidate directions rather than transforming the gradient.",
        "scope": "Global population-based",
        "already_covers": "Black-box candidate search and adaptation.",
        "difference_from_bcdo_reference": "BCDO is still first-order and cheap enough for neural training; it scores a small deterministic candidate set per block.",
        "required_baseline": "sgd_momentum",
    },
]
